### ISSUE TITLE
GraphQL format?

### ISSUE THREAD

**Issue by DonaldTsang** [nk2028/qieyun-sqlite#2]
Maybe this is something we can try to make Guangyun access easier to do?

**Comment by sgalal** [comment]
I published a plain JavaScript library. It would cover most of the use cases.

```html
<script src="https://cdn.jsdelivr.net/npm/qieyun/qieyun.min.js"></script>
```

The size of the library is less than 1 MB, which is satisfactory for most of the web applications. The actual transferred size (compressed) is less than 0.5 MB.

**Comment by sgalal** [comment]
This repository is renamed to [sgalal/qieyun-sqlite](https://github.com/sgalal/qieyun-sqlite).

The JavaScript library is split into a different repository: [sgalal/qieyun-js](https://github.com/sgalal/qieyun-js).

**Comment by sgalal** [comment]
I have made a [sgalal/qieyun-autoderiver](https://github.com/sgalal/qieyun-autoderiver) in JavaScript, using the [sgalal/qieyun-js](https://github.com/sgalal/qieyun-js) library. I believe the data is quite easy to access now.
